import { defineConfig } from 'vitepress'

// VitePress config for the qfs documentation site.
// srcDir is this `docs/` tree (the site is launched with `vitepress dev docs`), so the links
// below are relative to docs/. The reference pages (language/drivers/server) are GENERATED by
// `cargo run -p xtask -- gen-docs` from the binary's own registries — do not hand-edit them.
export default defineConfig({
  title: 'qfs',
  description: 'One small grammar for every external service.',
  // Generated reference docs cross-link each other relatively; don't fail the build on a link
  // VitePress can't statically resolve.
  ignoreDeadLinks: true,
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Language', link: '/language' },
      { text: 'Drivers', link: '/drivers' },
      { text: 'Server', link: '/server' },
      { text: 'ADRs', link: '/adr/0001-parser-library' },
    ],
    sidebar: [
      {
        text: 'Reference',
        items: [
          { text: 'Docs index', link: '/README' },
          { text: 'Language', link: '/language' },
          { text: 'Drivers', link: '/drivers' },
          { text: 'Server', link: '/server' },
        ],
      },
      {
        text: 'Architecture Decisions',
        items: [
          { text: '0001 — Parser library', link: '/adr/0001-parser-library' },
          { text: '0002 — Local combine engine', link: '/adr/0002-local-combine-engine' },
          { text: '0003 — Git object access', link: '/adr/0003-git-object-access' },
          { text: '0004 — HTTP serving', link: '/adr/0004-http-serving' },
          { text: '0005 — Deployment hosts', link: '/adr/0005-deployment-hosts' },
          { text: '0006 — Test harness', link: '/adr/0006-test-harness' },
          { text: '0007 — Docs and distribution', link: '/adr/0007-docs-and-distribution' },
        ],
      },
      {
        text: 'Security',
        items: [{ text: 'Threat model', link: '/security/threat-model' }],
      },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/qmu/qfs' }],
  },
})
